version: 0.0
os: linux
files:
  - source: /api-practice-0.0.1-SNAPSHOT.jar
    destination: /var/api-practice
hooks:
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location : /start_server.sh
      timeout: 300
      runas: ec2-user
